//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriendsBag.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbiInvoice
    {
        public int Invoice_Id { get; set; }
        public int Customer_Id { get; set; }
        public string Item_Name { get; set; }
        public decimal Amout { get; set; }
        public decimal Discount { get; set; }
        public int Quntity { get; set; }
        public decimal Total_Amount { get; set; }
        public System.DateTime Invoice_Date { get; set; }
        public string Payment_Mode { get; set; }
        public decimal IGST { get; set; }
        public decimal CGST { get; set; }
        public decimal SGST { get; set; }
    }
}
