//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriendsBag.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBill
    {
        public int Bill_Id { get; set; }
        public string Customer_Name { get; set; }
        public string Item_Name { get; set; }
        public int Quantity { get; set; }
        public decimal Amount { get; set; }
        public decimal Total_Amount { get; set; }
        public int Invoice_No { get; set; }
        public System.DateTime Date { get; set; }
        public string Payment_Mode { get; set; }
    }
}
