//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriendsBag.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrder
    {
        public int OrderId { get; set; }
        public int InvoicId { get; set; }
        public string Name { get; set; }
        public string MobileNo { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string colour { get; set; }
        public decimal Price { get; set; }
        public string PaymentMode { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public decimal TotalAmount { get; set; }
        public string OrderNotes { get; set; }
        public string Item { get; set; }
    }
}
